<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('horse backbone') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js') ?>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
    </div>
</nav>

<div class="container">
    <div id="app">
        <?php echo $this->content ?>
    </div>

    <hr>

    <footer>
        <p>&copy; 0 - 9000 by Horse Technologies Ltd. All rights reserved.</p>
    </footer>
</div>

<?php
echo file_get_contents(getcwd() . "/public/templates.html");
echo $this->inlineScript()->appendScript(
    'var ROUTES = ' . json_encode($this->routes) . ';'
);
echo $this->inlineScript()->prependFile($this->basePath() . '/js/app.js');
?>
</body>
</html>
